[General]
all-hybrid = true
ipv6 = true
geoip-maxmind-url = https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb
skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,localhost,*.local,*.bank,*.icbc,*.ccb,*.boc,*.cmbchina,*.955,*.cmpassport.com
always-real-ip = *.srv.nintendo.net,*.stun.playstation.net,xbox.*.microsoft.com,*.xboxlive.com,*.battlenet.com.cn,*.battlenet.com,*.blzstatic.cn,*.battle.net
bypass-system = true
doh-server = https://dns.alidns.com/dns-query,https://doh.pub/dns-query
dns-server = 223.5.5.5,114.114.114.114,2409:8088::1
tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.168.0.0/16,224.0.0.0/4
ipv6-disallow-outbound = true

[Proxy Group]
🌐 Direct = select,DIRECT
👋 Adblocks = select,REJECT,DIRECT
✈️ Proxy = select,🚀Auto,🇭🇰HK,🇨🇳TW,🇯🇵JP,🇸🇬SG,OtherWise,DIRECT
🚀Auto = url-test,🇭🇰HK,🇨🇳TW,🇯🇵JP,🇸🇬SG,update-interval=1800
🇭🇰HK = url-test,policy-regex-filter=(?=.*(香港|HK|HongKong))^((?!(专线|手游|游戏|game)).)*,update-interval=1800
🇨🇳TW = url-test,policy-regex-filter=(?=.*(台湾|TW|Taiwan))^((?!(专线|手游|游戏|game)).)*,update-interval=1800
🇯🇵JP = url-test,policy-regex-filter=(?=.*(日本|JP|Japan))^((?!(专线|手游|游戏|game)).)*,update-interval=1800
🇸🇬SG = url-test,policy-regex-filter=(?=.*(新加坡|SG|Singapore))^((?!(专线|手游|游戏|game)).)*,update-interval=1800
🇺🇸US = select,policy-regex-filter=(?=.*(美国|US|States))^((?!(专线|手游|游戏|game)).)*
OtherWise = select,policy-regex-filter=(?=.*(马|俄|印|德|菲|澳|法|韩))^((?!(专线|手游|游戏|game)).)*

[Rule]
# 银行直连，防风控
DOMAIN-SUFFIX,bank,🌐 Direct
DOMAIN-SUFFIX,icbc,🌐 Direct
DOMAIN-SUFFIX,ccb,🌐 Direct
DOMAIN-SUFFIX,abc,🌐 Direct
DOMAIN-SUFFIX,boc,🌐 Direct
DOMAIN-SUFFIX,cmbchina,🌐 Direct
DOMAIN-SUFFIX,cib,🌐 Direct
DOMAIN-SUFFIX,955,🌐 Direct
DOMAIN-SUFFIX,cmpassport.com,🌐 Direct

# 国内常用域名直连
DOMAIN-SUFFIX,qq.com,🌐 Direct
DOMAIN-SUFFIX,baidu.com,🌐 Direct
DOMAIN-SUFFIX,boc.cn,🌐 Direct
DOMAIN-SUFFIX,lan,🌐 Direct
DOMAIN-SUFFIX,local,🌐 Direct

# 内网网段不走代理
IP-CIDR,10.0.0.0/8,🌐 Direct,no-resolve
IP-CIDR,172.16.0.0/12,🌐 Direct,no-resolve
IP-CIDR,192.168.0.0/16,🌐 Direct,no-resolve
IP-CIDR,100.64.0.0/10,🌐 Direct,no-resolve

# IPv6管控
IP-CIDR6,fe80::/10,🌐 Direct,no-resolve
IP-CIDR6,::/0,REJECT,no-resolve

# 广告屏蔽规则
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/AdvertisingLite/AdvertisingLite.list,👋 Adblocks
DOMAIN-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/AdvertisingLite/AdvertisingLite_Domain.list,👋 Adblocks

# 海外平台分流
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Google/Google.list,🇺🇸US
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/YouTube/YouTube.list,🇺🇸US
DOMAIN-KEYWORD,google,🇺🇸US
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Proxy/Proxy.list,✈️ Proxy
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/GitHub/GitHub.list,🇭🇰HK
DOMAIN-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Proxy/Proxy_Domain.list,✈️ Proxy

# 兜底分流
GEOIP,CN,🌐 Direct
FINAL,✈️ Proxy

[URL Rewrite]
https://raw.githubusercontent.com/app2smile/rules/master/module/bilibili.sgmodule
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rewrite/Shadowrocket/AdvertisingLite/AdvertisingLite.sgmodule

#[Script]

# MITM已注释，如需抓包证书，删掉#号启用
# [MITM]
# hostname = *.googlevideo.com,*.google.cn
# ca-passphrase =
# ca-p12 =
# enable = false
